# Generated by Django 4.2.4 on 2025-04-14 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0002_default_leave_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='start_date',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='leave_attachments/'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='hod_line_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='relief_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relief_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LeavePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('duration', models.PositiveIntegerField()),
                ('end_date', models.DateField()),
                ('resumption_date', models.DateField()),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='leave.leaverequest')),
            ],
        ),
    ]
