# Generated by Django 4.2.4 on 2025-04-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_hod_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='is_relief_eligible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='location',
            field=models.CharField(choices=[('Lekki', 'Lekki'), ('Ikorodu', 'Ikorodu'), ('Ibeju_Lekki', 'Ibeju Lekki'), ('Portharcourt', 'Port Harcourt')], max_length=20, null=True),
        ),
    ]
