# Generated by Django 4.2.4 on 2025-04-14 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0029_member_is_hod_manager_member_is_relief_eligible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhisform',
            name='form_number',
            field=models.CharField(blank=True, null=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='nhisform',
            name='manager_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nhisform',
            name='manager_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhis_manager_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nhisform',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nhisform',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhis_rejections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nhisform',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nhisform',
            name='supervisor_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nhisform',
            name='supervisor_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nhis_supervisor_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nhisform',
            name='status',
            field=models.CharField(choices=[('awaiting_supervisor', 'Awaiting Supervisor Approval'), ('awaiting_manager', 'Awaiting Manager Approval'), ('approved', 'Approved'), ('rejected_by_supervisor', 'Rejected by Supervisor'), ('rejected_by_manager', 'Rejected by Manager')], default='awaiting_supervisor', max_length=25),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_form', 'New Form Submission'), ('approved', 'Form Approved'), ('rejected', 'Form Rejected'), ('comment', 'New Comment')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('nhis_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.nhisform')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NHISComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nhis_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.nhisform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
