# Generated by Django 5.2 on 2025-04-15 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_nhisform_form_number_nhisform_manager_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='ptw_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ptwform'),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='form_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='manager_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='manager_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ptw_manager_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ptw_rejections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='supervisor_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ptwform',
            name='supervisor_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ptw_supervisor_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ptwform',
            name='status',
            field=models.CharField(choices=[('awaiting_supervisor', 'Awaiting Supervisor Approval'), ('supervisor_signed', 'Supervisor Signed'), ('awaiting_manager', 'Awaiting Manager Approval'), ('manager_signed', 'Manager Signed'), ('approved', 'Approved'), ('rejected_by_supervisor', 'Rejected by Supervisor'), ('rejected_by_manager', 'Rejected by Manager'), ('disapproved', 'Disapproved')], default='awaiting_supervisor', max_length=30),
        ),
        migrations.CreateModel(
            name='PTWComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ptw_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.ptwform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
