# Generated by Django 5.2 on 2025-04-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_notification_ptw_form_ptwform_form_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nhisform',
            name='location',
            field=models.CharField(blank=True, choices=[('Lekki', 'Lekki'), ('Ikorodu', 'Ikorodu'), ('Ibeju_Lekki', 'Ibeju Lekki'), ('Portharcourt', 'Port Harcourt')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='nhisform',
            name='status',
            field=models.CharField(choices=[('awaiting_supervisor', 'Awaiting Supervisor Approval'), ('approved', 'Approved'), ('rejected_by_supervisor', 'Rejected by Supervisor'), ('awaiting_manager', 'Awaiting Manager Approval'), ('rejected_by_manager', 'Rejected by Manager')], default='awaiting_supervisor', max_length=25),
        ),
        migrations.AlterField(
            model_name='ptwform',
            name='location',
            field=models.CharField(blank=True, choices=[('Lekki', 'Lekki'), ('Ikorodu', 'Ikorodu'), ('Ibeju_Lekki', 'Ibeju Lekki'), ('Portharcourt', 'Port Harcourt')], max_length=255, null=True),
        ),
    ]
