# Generated by Django 4.2.4 on 2025-04-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_nhisform_location_alter_nhisform_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='location',
            field=models.CharField(choices=[('Lekki', 'HQ - Lekki'), ('Ikorodu', 'CGS - Ikorodu'), ('Ibeju_Lekki', 'Optimera - Ibeju Lekki'), ('Portharcourt', 'LPG - Port Harcourt')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='nhisform',
            name='location',
            field=models.CharField(blank=True, choices=[('Lekki', 'HQ - Lekki'), ('Ikorodu', 'CGS - Ikorodu'), ('Ibeju_Lekki', 'Optimera - Ibeju Lekki'), ('Portharcourt', 'LPG - Port Harcourt')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ptwform',
            name='location',
            field=models.CharField(blank=True, choices=[('Lekki', 'HQ - Lekki'), ('Ikorodu', 'CGS - Ikorodu'), ('Ibeju_Lekki', 'Optimera - Ibeju Lekki'), ('Portharcourt', 'LPG - Port Harcourt')], max_length=255, null=True),
        ),
    ]
